/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visuals;

import htmlConstruction.ComponenType;
import htmlConstruction.ComponentSubType;
import htmlConstruction.HtmlComponent;
import htmlConstruction.HtmlConstruction;
import htmlConstruction.JsConstruction;
import htmlconstructor.HtmlConstructor;
import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import nodos.NodoM;

/**
 *
 * @author RICARDO
 */
public class ProjectScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartVisualPage
     */
    
    public ProjectScreen(NodoM components, String tittle, String username)
    {
        this.components=components;
        this.title=tittle;
        ProjectScreen.userName=username;
        
        initComponents();
        
        this.setTitle(userName+" - PROYECT - "+tittle);
        this.reorganize();
    }
    
    public ProjectScreen(String tittle, String username) 
    {
        ProjectScreen.title=tittle;
        this.userName=username;
        
        initComponents();
        
        this.setTitle(userName+" - PROYECT - "+tittle);
    }

    public ProjectScreen() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentList = new javax.swing.JScrollPane();
        labelList = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inspectHtml = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inspectJs = new javax.swing.JTextArea();
        historialPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        historial = new javax.swing.JTextArea();
        agregar = new javax.swing.JPanel();
        elementType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        initialValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alto = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        ancho = new javax.swing.JSpinner();
        newelement = new javax.swing.JButton();
        preview = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        pruebaDeNavegador = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        elementComand = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        userOptions = new javax.swing.JMenu();
        userBack = new javax.swing.JMenuItem();
        proyectOptions = new javax.swing.JMenu();
        saveProyect = new javax.swing.JMenuItem();
        exportProyect = new javax.swing.JMenuItem();
        ftpProyect = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelList.setPreferredSize(new java.awt.Dimension(220, 4000));
        labelList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout labelListLayout = new javax.swing.GroupLayout(labelList);
        labelList.setLayout(labelListLayout);
        labelListLayout.setHorizontalGroup(
            labelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        labelListLayout.setVerticalGroup(
            labelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4000, Short.MAX_VALUE)
        );

        componentList.setViewportView(labelList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("NAVEGADOR", jPanel1);

        inspectHtml.setEditable(false);
        inspectHtml.setColumns(20);
        inspectHtml.setRows(5);
        jScrollPane2.setViewportView(inspectHtml);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("INSPECT HTML", jPanel2);

        inspectJs.setEditable(false);
        inspectJs.setColumns(20);
        inspectJs.setRows(5);
        jScrollPane3.setViewportView(inspectJs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("INSPECT JS", jPanel3);

        historial.setEditable(false);
        historial.setColumns(20);
        historial.setRows(5);
        jScrollPane5.setViewportView(historial);

        javax.swing.GroupLayout historialPanelLayout = new javax.swing.GroupLayout(historialPanel);
        historialPanel.setLayout(historialPanelLayout);
        historialPanelLayout.setHorizontalGroup(
            historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        historialPanelLayout.setVerticalGroup(
            historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("HISTORIAL", historialPanel);

        elementType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PARRAFO", "BOTÓN", "TEXTBOX", "CANVAS" }));
        elementType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("tipo de elemento html:");

        jLabel2.setText("valor inicial");

        initialValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialValueActionPerformed(evt);
            }
        });

        jLabel3.setText("altura");

        alto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel4.setText("ancho");

        ancho.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        newelement.setText("AGREGAR");
        newelement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newelementActionPerformed(evt);
            }
        });

        preview.setText("vista previa");
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });

        actualizar.setText("ACTUALIZAR NAVEGADOR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        pruebaDeNavegador.setColumns(20);
        pruebaDeNavegador.setRows(5);
        jScrollPane4.setViewportView(pruebaDeNavegador);

        javax.swing.GroupLayout agregarLayout = new javax.swing.GroupLayout(agregar);
        agregar.setLayout(agregarLayout);
        agregarLayout.setHorizontalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(actualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(elementType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agregarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(initialValue))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agregarLayout.createSequentialGroup()
                        .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(newelement, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agregarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(alto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agregarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        agregarLayout.setVerticalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(elementType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(initialValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newelement, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setMaximumSize(new java.awt.Dimension(170, 188));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("vista previa:");

        elementComand.setEditable(false);
        elementComand.setColumns(20);
        elementComand.setRows(5);
        jScrollPane1.setViewportView(elementComand);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        userOptions.setText("USUARIO");

        userBack.setText("regresar al menú de proyectos");
        userBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBackMouseClicked(evt);
            }
        });
        userBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBackActionPerformed(evt);
            }
        });
        userOptions.add(userBack);

        jMenuBar1.add(userOptions);

        proyectOptions.setText("PROYECTO");

        saveProyect.setText("exportar un archivo .hg");
        saveProyect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProyectActionPerformed(evt);
            }
        });
        proyectOptions.add(saveProyect);

        exportProyect.setText("exportProyect");
        proyectOptions.add(exportProyect);

        ftpProyect.setText("export by FTP");
        proyectOptions.add(ftpProyect);

        jMenuItem1.setText("agregar diseño");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        proyectOptions.add(jMenuItem1);

        jMenuBar1.add(proyectOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentList, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(componentList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBackMouseClicked
    }//GEN-LAST:event_userBackMouseClicked

    private void userBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBackActionPerformed
        HtmlConstruction.components= new NodoM();
        this.setVisible(false);
        HtmlConstructor.menu.setVisible(true);
        
        HtmlComponent.idComplement=0;
        
        HtmlConstruction.components=new NodoM();
        JsConstruction.events = new NodoM();
        
    }//GEN-LAST:event_userBackActionPerformed

    private void newelementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newelementActionPerformed
        
        HtmlComponent temporal = createComponent();
        
        HtmlConstruction.components.add(temporal);
        
        addLabel(temporal);
        
        reloadAll();
        
    }//GEN-LAST:event_newelementActionPerformed

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        
        vistaPrevia(createComponent().getElementComand());
        
    }//GEN-LAST:event_previewActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        ruta = pruebaDeNavegador.getText();
        ruta = ruta.replace('\\', '/');
        ruta = "file:///"+ruta;
        NavegadorPrueba navegadorPrueba = new NavegadorPrueba(ruta);
         
         navegadorPrueba.main();
         
        
        reloadAll();
    }//GEN-LAST:event_actualizarActionPerformed

    private void labelListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelListMouseClicked
        
        if(evt.getButton()==evt.BUTTON3)
        {
            try
            {
                elementOptions= new labelOptions(
                    ((javax.swing.JLabel)        
                    labelList.findComponentAt
                    (evt.getX()-1, evt.getY())));
            
                elementOptions.setLocation(evt.getLocationOnScreen());
                elementOptions.setVisible(true);
            }
            catch(Exception e)
            {
                //JOptionPane.showMessageDialog(null, "no hay ningún elemento aquí");
                elementOptions.setVisible(false);
            }
        }
        else
        {
            elementOptions.setVisible(false);
        }
    }//GEN-LAST:event_labelListMouseClicked

    private void saveProyectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProyectActionPerformed
        try
        {
            HtmlConstructor.saveHg();
        }
        catch(IOException error){}
    }//GEN-LAST:event_saveProyectActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        //if (!HtmlConstructor.vtnOpen) 
        //{
            HtmlConstructor.css.setVisible(true);
            
            //HtmlConstructor.vtnOpen=true;
        //}
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void elementTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementTypeActionPerformed

    private void initialValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialValueActionPerformed

    
    private HtmlComponent createComponent()
    {
        HtmlComponent temporal;
        
        switch(elementType.getSelectedIndex())
        {
            case 0:
                temporal= new HtmlComponent(ComponenType.OUTPUT, ComponentSubType.PARAGRAPH, initialValue.getText());
                break;
            case 1:
                temporal =  new HtmlComponent(
                            ComponenType.INPUT, 
                            ComponentSubType.BUTTON, 
                            initialValue.getText(), 
                            (int)ancho.getValue(), 
                            (int)alto.getValue() );
                break;
            case 2:
                temporal =  new HtmlComponent(
                            ComponenType.INPUT, 
                            ComponentSubType.TEXTBOX, 
                            initialValue.getText(), 
                            (int)ancho.getValue(), 
                            (int)alto.getValue() );
                break;
            default:
                temporal =  new HtmlComponent(
                            ComponenType.OUTPUT, 
                            ComponentSubType.CANVAS, 
                            initialValue.getText(), 
                            (int)ancho.getValue(), 
                            (int)alto.getValue() );
                break;
                
        }
        
        return temporal;
    }
    
    
    private void addLabel(HtmlComponent base)
    {
        javax.swing.JLabel nueva= new javax.swing.JLabel("  "+base.getLabelNum()+" "+base.getType());
        labelList.add(nueva);
        nueva.setBounds(x, y,180, 25);
        nueva.setOpaque(true);
        nueva.setForeground(Color.WHITE);
        nueva.setBackground(labelColDet? new Color(0,30,255): new Color(0,80,255));
        labelColDet = (!labelColDet);
        this.y=y+25;
        nueva.setVisible(true);
        
    }
    
    /**
     * recibe el comando específico de un elemento y muestra la vista previa
     * @param comando 
     */
    private void vistaPrevia(String comando)
    {
        
        elementComand.setText("\n\n"+comando+"     ");
    }
    
    public void reloadAll()
    {
        p.DocumentConstruction(title);
        
        try
        {
            reloadNav(p.getLink());
            reloadInspectHtml();
            reloadHistorial();
            reloadInspectJs();
        }
        catch(IOException errorDeArchivo)
        {}
    }
    
    /**
     * método para recargar el navegador a partir de una url
     * @param url 
     */
    private void reloadNav(String url)
    {
        //reemplazar esto por la funcionalidad del navegador
        pruebaDeNavegador.setText(url);
        
    }
    
    private void reloadInspectHtml()
            throws IOException
    {
        inspectHtml.setText("");
        
        BufferedReader inspect = new BufferedReader(new FileReader(title+".html"));
        
            String linea = inspect.readLine();
            
            while(linea!=null)
            {
                inspectHtml.append("    "+linea+"\n");
                linea = inspect.readLine();
            }
        
        inspect.close();
    }
    
    private void reloadInspectJs()
            throws IOException
    {
        inspectJs.setText("");
        
        BufferedReader inspect = new BufferedReader(new FileReader(title+".js"));
        
            String linea = inspect.readLine();
            
            while(linea!=null)
            {
                inspectJs.append("    "+linea+"\n");
                linea = inspect.readLine();
            }
        
        inspect.close();
    }
    
    private void reloadHistorial()
            throws IOException
    {
        historial.append("_________Archivo modificado en: "+LocalDateTime.now().toString()+"_______________\n\n");
        
        BufferedReader inspect = new BufferedReader(new FileReader(title+".html"));
        
            String linea = inspect.readLine();
            
            while(linea!=null)
            {
                historial.append("    "+linea+"\n");
                linea = inspect.readLine();
            }
        
        inspect.close();
        
        historial.append("\n___________________JavaScrpt events__________________\n");
        
        BufferedReader inspectjs = new BufferedReader(new FileReader(title+".js"));
        
            linea = inspectjs.readLine();
            
            while(linea!=null)
            {
                historial.append("    "+linea+"\n");
                linea = inspectjs.readLine();
            }
        
        inspectjs.close();
        
        historial.append("\n\n");
    }
    
//______________________________________________________________________________    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectScreen().setVisible(true);
            }
        });
    }

    
    private void reorganize()
    {
        //completar | reorganizar la lista de componentes respecto a un proyecto previamente creado |
    }
    
    
    private NodoM components=new NodoM();
    
    public static String  title;
    public static String userName;
    
    private int y=10,
                x=10;
    
    private boolean labelColDet=true;
    
    private static labelOptions elementOptions = new labelOptions();
    
    HtmlConstruction p = new HtmlConstruction();
    
    String ruta = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JPanel agregar;
    private javax.swing.JSpinner alto;
    private javax.swing.JSpinner ancho;
    private javax.swing.JScrollPane componentList;
    private javax.swing.JTextArea elementComand;
    private javax.swing.JComboBox<String> elementType;
    private javax.swing.JMenuItem exportProyect;
    private javax.swing.JMenuItem ftpProyect;
    private javax.swing.JTextArea historial;
    private javax.swing.JPanel historialPanel;
    private javax.swing.JTextField initialValue;
    private javax.swing.JTextArea inspectHtml;
    private javax.swing.JTextArea inspectJs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel labelList;
    private javax.swing.JButton newelement;
    private javax.swing.JButton preview;
    private javax.swing.JMenu proyectOptions;
    private javax.swing.JTextArea pruebaDeNavegador;
    private javax.swing.JMenuItem saveProyect;
    private javax.swing.JMenuItem userBack;
    private javax.swing.JMenu userOptions;
    // End of variables declaration//GEN-END:variables
}
